# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jaggr < Formula
  desc "JSON Aggregation CLI"
  homepage "https://github.com/rs/jaggr"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rs/jaggr/releases/download/1.0.1/jaggr_1.0.1_darwin_amd64v2.tar.gz"
      sha256 "04d07b6affa859fa77ba3422f2054fa9329cb52ebc5c7efc823913858d2cab84"

      def install
        bin.install "jaggr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rs/jaggr/releases/download/1.0.1/jaggr_1.0.1_darwin_arm64.tar.gz"
      sha256 "658d8c5f13d8e33c629e006ea0885dffbb8979aa8b88f5e00c36f79f1aab629e"

      def install
        bin.install "jaggr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rs/jaggr/releases/download/1.0.1/jaggr_1.0.1_linux_arm64.tar.gz"
      sha256 "edf49b835633525466f09613489e6aba7611037f0b5b1d89ab4352241600b599"

      def install
        bin.install "jaggr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rs/jaggr/releases/download/1.0.1/jaggr_1.0.1_linux_amd64v2.tar.gz"
      sha256 "d5fce32cf614b948da22906773e337729bead5f9cc1165f5c1539ea738620e84"

      def install
        bin.install "jaggr"
      end
    end
  end
end
