# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jplot < Formula
  desc "iTerm2 expvar/JSON monitoring tool"
  homepage "https://github.com/rs/jplot"
  version "2.2.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rs/jplot/releases/download/v2.2.2/jplot_2.2.2_darwin_amd64.tar.gz"
    sha256 "6af9f7f7aa641153b9244a3662e5cef4b75842452ed020945af75dec4454cd9b"

    def install
      bin.install "jplot"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rs/jplot/releases/download/v2.2.2/jplot_2.2.2_darwin_arm64.tar.gz"
    sha256 "02367598798415253be8046be0a00482cdfe256016440ae17f01406cf399a59b"

    def install
      bin.install "jplot"
    end
  end
end
