# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrinfo < Formula
  desc "QRCode info reader"
  homepage "https://github.com/rs/qrinfo"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/rs/qrinfo/releases/download/v1.0.0/qrinfo_1.0.0_darwin_amd64v2.tar.gz"
      sha256 "dd3dce7f4cbd17db6927ad183b7b2a7aadddb748f13e6c417e2c130eace20c16"

      def install
        bin.install "qrinfo"
      end
    end
    on_arm do
      url "https://github.com/rs/qrinfo/releases/download/v1.0.0/qrinfo_1.0.0_darwin_arm64.tar.gz"
      sha256 "e0bc0bc9efd9a47f8cc04bf8b5df02eb1987b93a48e5174cffb63e1fd3433899"

      def install
        bin.install "qrinfo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rs/qrinfo/releases/download/v1.0.0/qrinfo_1.0.0_linux_amd64v2.tar.gz"
        sha256 "3e1ffbcb0d1b6c0c6c4afa4fd724c10d61e59f4d6cf1efbe6fa741f75e50e8ce"

        def install
          bin.install "qrinfo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rs/qrinfo/releases/download/v1.0.0/qrinfo_1.0.0_linux_arm64.tar.gz"
        sha256 "0ee7658ec66d26255c1246c86b9bea375cad1029ab0ea2edc826337ce761a214"

        def install
          bin.install "qrinfo"
        end
      end
    end
  end
end
