# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrinfo < Formula
  desc "QRCode info reader"
  homepage "https://github.com/rs/qrinfo"
  version "1.0.6"

  on_macos do
    on_arm do
      url "https://github.com/rs/qrinfo/releases/download/v1.0.6/qrinfo_1.0.6_darwin_arm64.tar.gz"
      sha256 "545b48b50d79b30c5560e8e999ec2246cde4d17109b617b1632068e1acddb14a"

      def install
        bin.install "qrinfo"
      end
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rs/qrinfo/releases/download/v1.0.6/qrinfo_1.0.6_linux_arm64.tar.gz"
        sha256 "cd0935616f6270a8895fef6ca2e722953ea1eab5391b068461bed331c667e27c"

        def install
          bin.install "qrinfo"
        end
      end
    end
  end
end
